In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
WINDOW_MA = 10

Lectura de archivos

In [3]:
tweets_df = pd.read_csv("../data/tweets_with_sentiment_cryptobert.csv")
price_df = pd.read_csv("../data/datos_mercado_binance.csv")

In [4]:
tweets_df.head(5)

,Username,Text,Created At,Retweets,Likes,Sentiment
0,Peter McCormack üè¥‚Äç‚ò†Ô∏èüá¨üáßüáÆüá™,Happy New Year to you all.\n\nI hope you all h...,2023-01-01 01:49:27+00:00,8.0,450.0,1
1,Mohamed A. El-Erian,The notion of an exciting football game means ...,2023-01-01 01:55:27+00:00,3.0,419.0,1
2,Jimmy Song (ÏÜ°Ïû¨Ï§Ä),"10 years ago, I:\n\n* Bought more Bitcoin\n* S...",2023-01-01 06:48:00+00:00,21.0,531.0,1
3,Jameson Lopp,Bitcoin average DAILY value change during:\n20...,2023-01-01 12:50:57+00:00,35.0,231.0,0
4,Jameson Lopp,Bitcoin average DAILY value change during:\n20...,2023-01-01 12:50:57+00:00,35.0,231.0,0

In [5]:
price_df.head(5)

,simbolo,fecha,precio_apertura,precio_maximo,precio_minimo,precio_cierre,volumen
0,BTCUSDT,2023-01-01 00:00:00,16541.77,16628.00,16499.01,16616.75,96925.41374
1,BTCUSDT,2023-01-02 00:00:00,16617.17,16799.23,16548.70,16672.87,121888.57191
2,BTCUSDT,2023-01-03 00:00:00,16672.78,16778.40,16605.28,16675.18,159541.53733
3,BTCUSDT,2023-01-04 00:00:00,16675.65,16991.87,16652.66,16850.36,220362.18862
4,BTCUSDT,2023-01-05 00:00:00,16850.36,16879.82,16753.00,16831.85,163473.56641

In [6]:

tweets_df['fecha'] = pd.to_datetime(tweets_df['Created At'], errors='coerce')
# profe tips: revisar, la siguiente linea, porque parece redundante, ya que la linea anterior, en si misma convierte
# la data en fecha

# Asigna dia, mes y a√±o a la nueva columna fecha quitando la hora
tweets_df['fecha'] = tweets_df['fecha'].dt.date

price_df['fecha'] = pd.to_datetime(price_df['fecha'], errors='coerce')
tweets_df.head(5)

,Username,Text,Created At,Retweets,Likes,Sentiment,fecha
0,Peter McCormack üè¥‚Äç‚ò†Ô∏èüá¨üáßüáÆüá™,Happy New Year to you all.\n\nI hope you all h...,2023-01-01 01:49:27+00:00,8.0,450.0,1,2023-01-01
1,Mohamed A. El-Erian,The notion of an exciting football game means ...,2023-01-01 01:55:27+00:00,3.0,419.0,1,2023-01-01
2,Jimmy Song (ÏÜ°Ïû¨Ï§Ä),"10 years ago, I:\n\n* Bought more Bitcoin\n* S...",2023-01-01 06:48:00+00:00,21.0,531.0,1,2023-01-01
3,Jameson Lopp,Bitcoin average DAILY value change during:\n20...,2023-01-01 12:50:57+00:00,35.0,231.0,0,2023-01-01
4,Jameson Lopp,Bitcoin average DAILY value change during:\n20...,2023-01-01 12:50:57+00:00,35.0,231.0,0,2023-01-01

In [7]:
# We count by kind of feeling
count_sentiment = tweets_df.groupby(['fecha', 'Sentiment']).size().unstack(fill_value=0)

# We recalculate totals and average
count_sentiment['numero_noticias'] = count_sentiment.sum(axis=1)
count_sentiment['promedio_sentimiento'] = tweets_df.groupby('fecha')['Sentiment'].mean()

Transforma las columnas date en formato datetime.date

In [8]:
price_df['fecha'] = pd.to_datetime(price_df['fecha']).dt.date 
count_sentiment = count_sentiment.reset_index()  # si 'fecha' est√° en el √≠ndice
count_sentiment['fecha'] = pd.to_datetime(count_sentiment['fecha']).dt.date
count_sentiment.rename(
    columns={
        -1:'negative_sentiment_news',
        0:'neutral_sentiment_news',
        1:'positive_sentiment_news'
    },
    inplace=True
)

In [9]:
count_sentiment.head(5)

Sentiment,fecha,negative_sentiment_news,neutral_sentiment_news,positive_sentiment_news,numero_noticias,promedio_sentimiento
0,2023-01-01,0,10,5,15,0.333333
1,2023-01-02,0,2,0,2,0.000000
2,2023-01-03,0,5,3,8,0.375000
3,2023-01-04,2,4,5,11,0.272727
4,2023-01-05,1,6,6,13,0.384615

Realiza la fusi√≥n de los dos DataFrames (price_df y conteo_sentimientos) usando la columna fecha como clave

In [10]:
# We join by date
df_final = price_df.merge(count_sentiment, on='fecha', how='left')

In [11]:
df_final.head(5)

,simbolo,fecha,precio_apertura,precio_maximo,precio_minimo,precio_cierre,volumen,negative_sentiment_news,neutral_sentiment_news,positive_sentiment_news,numero_noticias,promedio_sentimiento
0,BTCUSDT,2023-01-01,16541.77,16628.00,16499.01,16616.75,96925.41374,0.0,10.0,5.0,15.0,0.333333
1,BTCUSDT,2023-01-02,16617.17,16799.23,16548.70,16672.87,121888.57191,0.0,2.0,0.0,2.0,0.000000
2,BTCUSDT,2023-01-03,16672.78,16778.40,16605.28,16675.18,159541.53733,0.0,5.0,3.0,8.0,0.375000
3,BTCUSDT,2023-01-04,16675.65,16991.87,16652.66,16850.36,220362.18862,2.0,4.0,5.0,11.0,0.272727
4,BTCUSDT,2023-01-05,16850.36,16879.82,16753.00,16831.85,163473.56641,1.0,6.0,6.0,13.0,0.384615

CALCULO MEDIA MOVIL CON DERIVADA Y TENDENCIA

In [12]:

# We added trend column
df_final['media_movil_10d'] = df_final['precio_apertura'].rolling(WINDOW_MA).mean()

# PROFE TIPS: la derivada hecha con la funcion diff no es la mejor opcion
# revisar otras funciones de derivadas
df_final['derivada_mm10'] = df_final['media_movil_10d'].diff()
condition_list = [
    df_final['derivada_mm10'].isna(),
    df_final['derivada_mm10'] > 0,
    df_final['derivada_mm10'] < 0,
]
returns_values_list = [0, 1, -1]
df_final['tendencia_categorizada'] = np.select(condition_list, returns_values_list, 0)
#def clasificar_derivada(valor):
#    if pd.isna(valor):
#        return 0  
#    elif valor > 0:
#        return 1
#    elif valor < 0:
#        return -1
#    else:
#        return 0
#df_final['tendencia_categorizada'] = df_final['derivada_mm10'].apply(clasificar_derivada)

üìà Indicador RSI (Relative Strength Index)

üìä RSI toma valores entre 0 y 100:

- (<30) podr√≠a indicar sobreventa.
- (>70) podr√≠a indicar sobrecompra.

In [13]:
# PROFE TIPS: trata de no usar funciones creadas por ti para los indicadores

def calculate_rsi(series, window=10):
    delta = series.diff()
    ganancias = delta.clip(lower=0)
    perdidas = -delta.clip(upper=0)

    media_ganancia = ganancias.rolling(window).mean()
    media_perdida = perdidas.rolling(window).mean()

    rs = media_ganancia / media_perdida
    rsi = 100 - (100 / (1 + rs))
    return rsi

df_final['RSI_10'] = calculate_rsi(df_final['precio_apertura'])

üîÅ Indicador MACD (Moving Average Convergence Divergence)

In [14]:
# EMA r√°pida y lenta
ema_12 = df_final['precio_apertura'].ewm(span=12, adjust=False).mean()
ema_26 = df_final['precio_apertura'].ewm(span=26, adjust=False).mean()

# L√≠nea MACD y se√±al
df_final['MACD'] = ema_12 - ema_26
df_final['MACD_signal'] = df_final['MACD'].ewm(span=9, adjust=False).mean()

In [15]:
df_final

,simbolo,fecha,precio_apertura,precio_maximo,precio_minimo,precio_cierre,volumen,negative_sentiment_news,neutral_sentiment_news,positive_sentiment_news,numero_noticias,promedio_sentimiento,media_movil_10d,derivada_mm10,tendencia_categorizada,RSI_10,MACD,MACD_signal
0,BTCUSDT,2023-01-01,16541.77,16628.00,16499.01,16616.75,96925.41374,0.0,10.0,5.0,15.0,0.333333,NaN,NaN,0,NaN,0.000000,0.000000
1,BTCUSDT,2023-01-02,16617.17,16799.23,16548.70,16672.87,121888.57191,0.0,2.0,0.0,2.0,0.000000,NaN,NaN,0,NaN,6.014815,1.202963
2,BTCUSDT,2023-01-03,16672.78,16778.40,16605.28,16675.18,159541.53733,0.0,5.0,3.0,8.0,0.375000,NaN,NaN,0,NaN,15.094857,3.981342
3,BTCUSDT,2023-01-04,16675.65,16991.87,16652.66,16850.36,220362.18862,2.0,4.0,5.0,11.0,0.272727,NaN,NaN,0,NaN,22.265775,7.638228
4,BTCUSDT,2023-01-05,16850.36,16879.82,16753.00,16831.85,163473.56641,1.0,6.0,6.0,13.0,0.384615,NaN,NaN,0,NaN,41.567254,14.424034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,BTCUSDT,2025-05-27,109434.78,110718.00,107516.57,108938.17,21276.65635,1.0,10.0,8.0,19.0,0.368421,107686.404,597.088,1,67.395337,3769.126180,3868.602046
878,BTCUSDT,2025-05-28,108938.17,109284.70,106769.43,107781.78,15633.78829,2.0,24.0,13.0,39.0,0.282051,108267.556,581.152,1,66.775298,3639.414671,3822.764571
879,BTCUSDT,2025-05-29,107781.78,108891.91,105322.86,105589.75,19834.70116,7.0,25.0,13.0,45.0,0.133333,108400.307,132.751,1,54.381097,3404.066398,3739.024936
880,BTCUSDT,2025-05-30,105589.75,106313.12,103621.00,103985.48,23706.49799,0.0,16.0,6.0,22.0,0.272727,108401.909,1.602,1,50.048658,3006.021155,3592.424180
881,BTCUSDT,2025-05-31,103985.47,104900.00,103068.55,104591.88,11289.35922,1.0,21.0,9.0,31.0,0.258065,108115.456,-286.453,-1,41.469500,2531.928942,3380.325132

Creaci√≥n df con indicadores finales

In [16]:
# Selecting final columns
df_csv = df_final[['fecha',
                    'precio_apertura',
                    'media_movil_10d', 
                    'RSI_10', 'MACD_signal', 
                    'tendencia_categorizada', 
                    'numero_noticias', 
                    'negative_sentiment_news', 
                    'neutral_sentiment_news', 
                    'positive_sentiment_news', 
                    'promedio_sentimiento']]

# We rename columns
df_csv.columns = ['date', 
                  'open',
                  'MA',
                  'RSI',
                  'MACD', 
                  'trend', 
                  'issue_news', 
                  'negative_sentiment_news', 
                  'neutral_sentiment_news', 
                  'positive_sentiment_news', 
                  'average_news']

In [17]:
df_final.head(5)

,simbolo,fecha,precio_apertura,precio_maximo,precio_minimo,precio_cierre,volumen,negative_sentiment_news,neutral_sentiment_news,positive_sentiment_news,numero_noticias,promedio_sentimiento,media_movil_10d,derivada_mm10,tendencia_categorizada,RSI_10,MACD,MACD_signal
0,BTCUSDT,2023-01-01,16541.77,16628.00,16499.01,16616.75,96925.41374,0.0,10.0,5.0,15.0,0.333333,NaN,NaN,0,NaN,0.000000,0.000000
1,BTCUSDT,2023-01-02,16617.17,16799.23,16548.70,16672.87,121888.57191,0.0,2.0,0.0,2.0,0.000000,NaN,NaN,0,NaN,6.014815,1.202963
2,BTCUSDT,2023-01-03,16672.78,16778.40,16605.28,16675.18,159541.53733,0.0,5.0,3.0,8.0,0.375000,NaN,NaN,0,NaN,15.094857,3.981342
3,BTCUSDT,2023-01-04,16675.65,16991.87,16652.66,16850.36,220362.18862,2.0,4.0,5.0,11.0,0.272727,NaN,NaN,0,NaN,22.265775,7.638228
4,BTCUSDT,2023-01-05,16850.36,16879.82,16753.00,16831.85,163473.56641,1.0,6.0,6.0,13.0,0.384615,NaN,NaN,0,NaN,41.567254,14.424034

In [18]:
df_csv.head(5)

,date,open,MA,RSI,MACD,trend,issue_news,negative_sentiment_news,neutral_sentiment_news,positive_sentiment_news,average_news
0,2023-01-01,16541.77,NaN,NaN,0.000000,0,15.0,0.0,10.0,5.0,0.333333
1,2023-01-02,16617.17,NaN,NaN,1.202963,0,2.0,0.0,2.0,0.0,0.000000
2,2023-01-03,16672.78,NaN,NaN,3.981342,0,8.0,0.0,5.0,3.0,0.375000
3,2023-01-04,16675.65,NaN,NaN,7.638228,0,11.0,2.0,4.0,5.0,0.272727
4,2023-01-05,16850.36,NaN,NaN,14.424034,0,13.0,1.0,6.0,6.0,0.384615

Creaci√≥n ventana deslizante

In [ ]:
# Features
colums_windows = ['open','MA','RSI','MACD', 'trend', 'issue_news', 
                    'negative_sentiment_news', 'neutral_sentiment_news', 'positive_sentiment_news', 'average_news']
# Tama√±o de la ventana
ventana = 5 

# Lista para almacenar las wind
wind = []

# Recorremos desde el d√≠a 1 hasta len (cantidad de filas del df) - ventana 
for i in range(len(df_csv) - ventana):
    # Extraemos las filas de la ventana anterior (d√≠as pasados)
    segment = df_csv[colums_windows].iloc[i:i+ventana]
    
    # Aplanamos los datos de la ventana en una sola fila
    row_wind = segment.values.flatten()
    
    # D√≠a objetivo y precio objetivo: el siguiente d√≠a despu√©s de la ventana
    target_day = df_csv['date'].iloc[i + ventana]
    target_price = df_csv['open'].iloc[i + ventana]

    # Se crea la fila con target_date, target_price y la ventana
    wind.append([target_day, target_price] + row_wind.tolist())

# Se crea las 2 columnas de target
columns_name = ['target_date', 'target_price']
# Generacion de columnas "open_d1, RS1_d1, open_d2, etc" de la ventana deslizante
for dia in range(ventana):
    for col in colums_windows:
        columns_name.append(f'{col}_d{dia+1}')

Exportar csv

In [20]:
# DataFrame final
df_sliding_window = pd.DataFrame(wind, columns=columns_name)

# Exportar a CSV
df_sliding_window.to_csv('../data/final_data_copy.csv', index=False)